[theme]
theme = "modern"
[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:15) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20) $prev $play $next |}"
player = "spotify"

[[block]]
block = "docker"
interval = 2
format = " $icon $running"

[[block]]
block = "amd_gpu"
format = " $icon $utilization "
format_alt = " $icon MEM: $vram_used_percents ($vram_used/$vram_total) "
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
format = " $icon $ip ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K)"
interval = 5

[[block]]
block = "sound"
max_vol = 100
device_kind = "source"
headphones_indicator = true

[[block]]
block = "sound"
max_vol = 100
device_kind = "sink"

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"

[[block]]
block = "time"
interval = 15
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R', l:de_DE) "
short = " $icon $timestamp.datetime(f:%R) "

# [[block]]
# block = "custom"
# command = "echo \uf0c2" # icon is for nerdfont, replace if other
# [[block.click]]
# button = "left"
# cmd = "nextcloud"
