theme = "nord-dark"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 25
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "networkmanager"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "sound"
max_vol = 100
device_kind = "source"
headphones_indicator = true

[[block]]
block = "sound"
max_vol = 100
device_kind = "sink"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
