theme = "slick"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 25
show_marks = "visible"

[[block]]
block = "music"
player = "spotify"
buttons = ["play"]

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
format = "{ip} {speed_down;K*b} {speed_up;K*b}"
interval = 5

[[block]]
block = "backlight"
invert_icons = true

[[block]]
block = "sound"
max_vol = 100
device_kind = "source"
headphones_indicator = true

[[block]]
block = "sound"
max_vol = 100
device_kind = "sink"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "notify"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
