modmap:                                                                                                                                                                                                       
  - name: Default
    remap: # Required
      # Replace a key with another
      KEY_CAPSLOCK: KEY_LEFTMETA # Required